#!/usr/bin/env python3
"""Compile exact archived genomes into data-only catalog snapshots. No optimization."""
from pathlib import Path
import runpy,hashlib,json
root=Path(__file__).resolve().parents[1];io=runpy.run_path(str(Path(__file__).with_name('discovery-genomes.py')))
entries=[('Skiff',.09,'A small swimmer follows food.'),('Thread',.34,'A trailing body gathers passing food.'),('Whorl',.57,'Three arms turn through food.'),('Husk',.70,'Stores a feast. Place among food.')]
def f(v):
    s=format(v,'.9g')
    return s+('f' if '.' in s or 'e' in s else '.0f')
def val(k,v):
    enums={'role':'CellRole','waveform':'Waveform','motorMode':'MotorMode','memoryMode':'MemoryMode'}
    if k in enums:return f'{enums[k]}({int(v)})'
    if k=='neural':return 'true' if v else 'false'
    if k=='motorChannel':return str(int(v))
    return f(v)
lines=['// Generated by scripts/export-discovered-catalog.py from archived real descendants.','// Do not tune here: replay/search, select an archive, then regenerate.','#include "alienmobile/Genome.h"','namespace alienmobile {','std::vector<SpecimenSnapshot> makeCuratedSpecimenCatalog() {','    std::vector<SpecimenSnapshot> result;']
provenance=[]
for name,hue,description in entries:
    p=root/'docs/discovery/finalists'/(name+'.dna');g=io['read'](p);sha=hashlib.sha256(p.read_bytes()).hexdigest();provenance.append(dict(name=name,sha256=sha))
    lines+=['    {',f'    // {name}: DNA sha256 {sha}','    Genome genome;',f'    genome.entryGene={g["entry"]};',f'    genome.genes.resize({len(g["genes"])});']
    for k,v in g['rates'].items():lines.append(f'    genome.mutationRates.{k}={f(v)};')
    for gi,gene in enumerate(g['genes']):
        lines += ['    {',f'    auto& gene=genome.genes[{gi}];',f'    gene.orientation={f(gene["orientation"])};gene.phaseAdvance={f(gene["phase"])};',f'    gene.nodes.resize({len(gene["nodes"])});']
        for ni,n in enumerate(gene['nodes']):
            lines+=['    {',f'    auto& node=gene.nodes[{ni}];',f'    node.parentNode={int(n["parent"])};node.relativePosition={{{f(n["x"])},{f(n["y"])}}};',f'    node.constructorCell={"true" if n["constructor"] else "false"};node.stiffness={f(n["stiffness"])};']
            for src,dst in [('target','targetGene'),('branches','branches'),('repetitions','repetitions'),('angle','angle'),('branchAngle','branchAngle'),('repetitionAngle','repetitionAngle'),('intervalScale','intervalScale'),('separate','separateOffspring')]:
                v=('true' if n[src] else 'false') if src=='separate' else str(int(n[src])) if src in ['target','branches','repetitions'] else f(n[src]);lines.append(f'    node.construction.{dst}={v};')
            for k in io['fields']:lines.append(f'    node.behavior.{k}={val(k,n[k])};')
            lines.append('    node.behavior.weights={'+','.join('Signals{'+','.join(f(v) for v in n['weights'][i:i+8])+'}' for i in range(0,64,8))+'};')
            lines.append('    node.behavior.biases={'+','.join(f(v) for v in n['biases'])+'};');lines.append('    }')
        lines.append('    }')
    lines += [f'    result.push_back({{"{name}",std::move(genome),{f(hue)},1.0f,"{description}"}});','    }']
lines+=['    return result;','}','} // namespace alienmobile']
(root/'core/src/CatalogGenomes.cpp').write_text('\n'.join(lines)+'\n')
(root/'docs/discovery/finalists/checksums.json').write_text(json.dumps(provenance,indent=2)+'\n')
